name: caladan properties
favicon: null
layout_spectrum: 0.87503
typography_spectrum: 0.13751
title: Managed Properties
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#7a7174'
    - '#bec8d4'
    - '#303030'
    - '#a49b9e'
  brandStrength: 0.1875
  lightness: 0.4375
  saturation: 0.1875
  rhythmicContrast: 0.6838173733558506
purpose: []
